// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryApp.DataAccess
{
    public partial class ContactType
    {
        public ContactType()
        {
            CustomerContacts = new HashSet<CustomerContact>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
    }
}