// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryApp.DataAccess
{
    public partial class Customer
    {
        public Customer()
        {
            CustomerContacts = new HashSet<CustomerContact>();
            ItemHistories = new HashSet<ItemHistory>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        public virtual ICollection<ItemHistory> ItemHistories { get; set; }
    }
}