// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryApp.DataAccess
{
    public partial class CustomerContact
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int TypeId { get; set; }
        public string Value { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ContactType Type { get; set; }
    }
}