// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryApp.DataAccess
{
    public partial class ItemHistory
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int CustomerId { get; set; }
        public DateTime CheckIn { get; set; }
        public bool IsLate { get; set; }
        public decimal? LateFees { get; set; }
        public bool IsDamaged { get; set; }
        public decimal? Fines { get; set; }
        public string Notes { get; set; }
        public DateTime CheckOut { get; set; }
        public DateTime DueDate { get; set; }
        public int RenewalCount { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
    }
}